version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=AppointmentDB;Username=postgres;Password=postgres

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: AppointmentDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

